# Generated by Django 6.0.7 on 2026-07-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xaiexplanation',
            name='base_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
